### ISSUE TITLE
Empty room causes unhandled exception

### ISSUE THREAD

**Issue by TinyAngryKitten** [InkApplications/Shade#56]
### Shade Info:
 - Version: 1.1.0

### How to Reproduce the Issue:
First create a room in hue without a light.

```
fun main() {
val shade = Shade()
runBlocking {
                shade.setBaseUrl("somebaseurl")
                shade.auth.awaitToken()
                shade.groups.getGroups().forEach { (id, light) ->
                    println("Found Group $id named ${light.name}")
                }
       }
}
```
Expected behavior:
should print all groups ids and their names

Actual behavior:
throws an unhandled exception: 

SEVERE: Unhandled exception
com.squareup.moshi.JsonDataException: Required property 'brightness' missing at $.4.action
at inkapplications.shade.lights.LightStateJsonAdapter.fromJson(LightStateJsonAdapter.kt:92)
at inkapplications.shade.lights.LightStateJsonAdapter.fromJson(LightStateJsonAdapter.kt:17)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
at inkapplications.shade.groups.Group_RoomJsonAdapter.fromJson(Group_RoomJsonAdapter.kt:57)
at inkapplications.shade.groups.Group_RoomJsonAdapter.fromJson(Group_RoomJsonAdapter.kt:16)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.fromJson(PolymorphicJsonAdapterFactory.java:197)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:69)
at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:30)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)

I suspect that this happens because there are rooms without lights in my hue setup.
This is the response from hue [/api/groups](https://pastebin.com/DzFdPd4s) where both Bedroom and Bathroom 
has no action.brightness because there are no lights in them. The issue was resolved by removing the rooms without lights.

**Comment by ReneeVandervelde** [comment]
Thanks for the detailed report! 🙌 
Was able to reproduce and this should be fixed in version 1.1.1 🎉
