### ISSUE TITLE
UpdateState::lastInstall should be optional

### ISSUE THREAD

**Issue by liviomarti** [InkApplications/Shade#59]
Getting following StackTrace when light are being loaded (`shade.lights.getLights().forEach{...}`):
```
Exception in thread "main" com.squareup.moshi.JsonDataException: Non-null value 'lastInstall' (JSON name 'lastinstall') was 
null at $.1.swupdate.lastinstall
	at com.squareup.moshi.internal.Util.unexpectedNull(Util.java:628)
	at inkapplications.shade.lights.UpdateStateJsonAdapter.fromJson(UpdateStateJsonAdapter.kt:40)
	...
```

My Philips Hue setup contains some older LivingColors devices, in which case the property 'lastinstall' is null.
This property should therefore be optional: 
`val lastInstall: Instant?`

**Comment by ReneeVandervelde** [comment]
Thanks for the report! This should be fixed in version 1.1.3, which I've just tagged.
Open more bugs if you find them. Hue's documentation is unfortunately pretty non-existent on the format of some of the older hardware. 😞
