### ISSUE TITLE
N-UPNP Endpoint is retired

### ISSUE THREAD

**Issue by ReneeVandervelde** [InkApplications/Shade#60]
### Shade Info:
 - Version: 1.1.1

### How to Reproduce the Issue:

Example:
```shell
shade discover
```

Expected behavior:

This should list the available endpoints.
This also affects the SDK in the same fashion, with a similar stack trace

Actual behavior:

```
$ shade discover
Unknown Error: HTTP 404 
retrofit2.HttpException: HTTP 404 
        at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by ReneeVandervelde** [comment]
This is fixed in 1.1.2
